## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Read data

In [2]:
data = pd.read_csv("creditcard.csv")
data.sample(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
212915,139039.0,-4.040413,2.622909,-2.443762,-0.967314,-1.199774,-1.472900,-0.376405,1.827454,0.432744,...,-0.145790,-0.286458,0.044423,-0.181841,0.201900,-0.154048,-0.452963,-0.260418,25.00,0
62476,50282.0,-0.830893,0.702480,1.832422,-0.426275,-1.243311,-0.250197,-0.138399,0.438705,0.278531,...,0.023231,0.089003,-0.018313,0.469419,-0.311316,0.937541,-0.215425,-0.022664,55.95,0
185753,126810.0,0.308615,-0.469102,-1.550750,-2.051320,1.370651,-0.837395,1.780701,-1.095026,-1.192660,...,0.394021,1.537766,0.024027,0.133886,-1.412091,-0.412820,-0.051846,-0.132106,164.95,0
35215,38018.0,1.191142,-0.335213,-0.344326,-0.881741,-0.365378,-0.892940,0.175858,-0.141745,1.065129,...,0.033961,0.164916,-0.284323,0.022493,0.925290,-0.549738,0.016513,0.005390,55.48,0
77449,57055.0,-0.355680,0.909893,1.180642,-0.213030,0.193505,-0.454046,0.584199,0.076039,-0.100581,...,-0.300767,-0.877621,-0.105111,-0.517403,-0.135066,0.128447,0.253706,0.109159,3.59,0

### Exploratory data Analysis

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [4]:
data.shape

(284807, 31)

In [5]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [6]:
data['Time'].value_counts()

163152.0    36
64947.0     26
68780.0     25
3767.0      21
3770.0      20
            ..
127750.0     1
62260.0      1
62259.0      1
127753.0     1
172792.0     1
Name: Time, Length: 124592, dtype: int64

In [7]:
# distribution of legit transaction and fraudlent transaction
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
# Compare the values for both transactions
data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Frauds transactions are more than the legit transactions

### Data Preprocessing

In [9]:
df = data.copy()

In [10]:
# separating the data for analysis and data sample creation
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [11]:
print("Fraud Transactions: ",fraud.shape)
print("Legit Transactions: ", legit.shape)

Fraud Transactions:  (492, 31)
Legit Transactions:  (284315, 31)

In [12]:
## Take a sample of atleast 90% more of the Fraud transaction to reduce biasness in the data
legit_sample = legit.sample(n=4920)

## Do for another datasets for federated learning
legit_sample1 = legit.sample(n=4000)

In [13]:
# Concatenante the legit sample and the fraud to create a less biased dataset
import random

dfs = [legit_sample, fraud]
random.shuffle(dfs)
new_df = pd.concat(dfs, axis=0)

## Do for another datasets for federated learning
dfs = [legit_sample1, fraud]
random.shuffle(dfs)
df1 = pd.concat(dfs, axis=0)


new_df.shape

(5412, 31)

In [14]:
df1

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
57511,47940.0,-2.454371,-0.530124,0.536537,-0.880329,-1.478787,1.034731,0.595906,0.906780,-0.018294,...,-0.043189,-0.415314,-0.022431,-0.728832,0.070925,0.818496,-0.186132,-0.319256,347.25,0
276546,167158.0,2.077585,-0.171763,-1.484913,0.069503,0.377610,-0.310130,0.048989,-0.107500,0.395936,...,-0.303819,-0.802401,0.199196,-1.044822,-0.205036,0.241956,-0.079142,-0.079886,8.73,0
135389,81230.0,1.092632,-0.501921,0.978936,0.023468,-0.756248,0.625159,-0.751185,0.311447,0.849225,...,-0.149970,-0.201154,0.022373,-0.199633,0.091558,0.969157,-0.022179,0.004174,37.73,0
108452,70907.0,0.030371,1.603173,-2.217304,1.610322,1.253953,-0.125151,0.216585,0.725883,-0.363643,...,0.035721,0.325625,0.440859,-1.008099,-0.802894,-0.295564,0.081967,-0.077848,9.95,0
170723,120325.0,1.995590,0.480158,-2.284514,1.384684,0.989221,-0.756335,0.567087,-0.202671,-0.102722,...,0.006426,0.176079,-0.000218,0.634509,0.452713,-0.546836,-0.009242,-0.032061,6.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [15]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95403.432724,0.064396,-0.015935,0.005381,-0.029717,-0.008624,0.007480,-0.005705,-0.021437,0.027551,...,-0.028142,-0.005187,0.009653,0.002804,0.013108,-0.000163,-0.004985,-0.000048,0.008090,83.774833
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [16]:
X = new_df.drop(columns = 'Class',axis = 1)
y = new_df['Class']

### Modelling

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, stratify = y, random_state = 23)
print(X_train.shape, X_test.shape, y_train.shape,y_test.shape)

(4329, 30) (1083, 30) (4329,) (1083,)

In [19]:
lr =  LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [20]:
preds = lr.predict(X_test)

In [21]:
pred = accuracy_score(preds, y_test)
pred

0.9806094182825484

In [22]:
# Create new data out of the samples
new_df.to_csv("data1.csv")
df1.to_csv("credit.csv")

In [31]:
df2 = []

(284807, 31)

### Using SMOTE to solve data imbalance

In [23]:
from typing import Counter
from imblearn.over_sampling import SMOTE

counter =  Counter(y)
print('Before:', counter)

# oversampling the dataset using SMOTE
smt = SMOTE()
x_sm, y_sm = smt.fit_resample(X, y)

counter = Counter(y_sm)
print('After:', counter)

Before: Counter({0: 4920, 1: 492})
After: Counter({1: 4920, 0: 4920})

In [24]:
print(y_sm.shape, y.shape)

(9840,) (5412,)

In [25]:
print(x_sm.shape, X.shape)

(9840, 30) (5412, 30)

In [26]:
X_train1,X_test1,y_train1,y_test1 = train_test_split(x_sm,y_sm,test_size = 0.2, stratify = y_sm, random_state = 23)
print(X_train.shape, X_test.shape, y_train.shape,y_test.shape)

(4329, 30) (1083, 30) (4329,) (1083,)

In [27]:
model =  LogisticRegression()
model.fit(X_train1,y_train1)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()

In [28]:
preds = lr.predict(X_test1)

In [29]:
pred = accuracy_score(preds, y_test1)
pred

0.959349593495935

In [34]:
x_sm

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,406.000000,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.126911,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.000000
1,472.000000,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,2.102339,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.000000
2,4462.000000,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.430022,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.930000
3,6986.000000,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,-0.171608,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.000000
4,7519.000000,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,0.009061,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,132999.155503,-1.069376,-1.875696,-5.820460,3.004982,-0.655496,-1.640173,1.525091,-0.610307,-1.545953,...,2.414406,1.180369,0.171497,-1.310320,-0.318005,0.679963,-0.267530,0.176652,0.327756,1191.184921
9836,25282.360458,-11.930394,8.062857,-14.852556,5.137159,-9.334276,-3.105399,-10.316859,8.253830,-3.320925,...,1.094080,1.227369,-0.985758,-0.530534,-0.076262,0.923046,-0.160743,1.261775,0.393475,74.644272
9837,93853.000000,-5.839192,7.151532,-12.816760,7.031115,-9.651272,-2.938427,-11.543207,4.843627,-3.494276,...,0.055684,2.462056,1.054865,0.530481,0.472670,-0.275998,0.282435,0.104886,0.254417,316.060000
9838,43200.724461,-3.832687,2.082684,-5.157686,2.315898,-3.530289,-1.090420,-3.197034,-0.312467,-1.337423,...,-0.268902,1.464195,-0.070912,0.403930,-0.165732,0.229649,-0.593778,0.345819,-0.529191,335.334126
9839,77185.544803,-1.223948,2.120636,-2.034531,1.892916,0.569216,-1.090895,-1.031403,0.922580,-1.178937,...,0.101522,0.072389,-0.627818,-0.208688,-0.587399,0.145589,-0.426200,0.327643,0.172391,1.000000